version: '3.8'

services:
  db:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    command: mongod --auth
    volumes:
      - mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongo

volumes:
  mongo:
